package br.com.modtiktok.tiktokchaos.rule;

public enum ActionType {
    SPAWN_ENTITY,
    GIVE_ITEM,
    APPLY_EFFECT,
    SHORT_TELEPORT,
    COSMETIC_LIGHTNING,
    SET_WEATHER,
    MESSAGE,
    RANDOM_SAFE_ITEM,
    RANDOM_POSITIVE_EFFECT,
    RANDOM_NEGATIVE_EFFECT,
    PLAY_SOUND,
    LAUNCH_PLAYER,
    FREEZE_PLAYER,
    PARTICLE_BURST,
    CENTER_MESSAGE,
    VISUAL_ITEM_RAIN,
    GIFT_CANNON,
    LIKE_FOUNTAIN,
    SPAWN_VIEWER_BOSS,
    REVERSIBLE_BLOCK_BOX,
    MOD_INTEGRATION
}
